openapi: 3.0.0
info:
  title: Sample App
  version: 0.1.0
paths:
  /health:
    get:
      responses:
        '200':
          description: ok
  /users:
    get:
      responses:
        '200':
          description: list users
