version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: automation
      POSTGRES_PASSWORD: automation
      POSTGRES_DB: automation
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automation"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: ./backend
    command: air -c .air.toml # live reload with cosmtrek/air
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://automation:automation@postgres:5432/automation?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PORT: "8080"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
