services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.54
    container_name: openhands-app
    restart: unless-stopped
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: "docker.all-hands.dev/all-hands-ai/runtime:0.54-nikolaik"
      LOG_ALL_EVENTS: "true"
      OPENHANDS_LLM_BASE_URL: "http://host.docker.internal:11434/v1"
      OPENHANDS_LLM_API_KEY: "dummy"
      OPENHANDS_LLM_MODEL: "codellama:latest"
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPENHANDS_HOME}/.openhands:/.openhands
    extra_hosts:
      - "host.docker.internal:host-gateway"
